const fs = require('fs');
const path = require('path');

// Load environment variables from .env if it exists
try {
  if (fs.existsSync('.env')) {
    require('dotenv').config();
    console.log('✅ Loaded variables from .env');
  } else {
    console.log('💡 No .env file found, using system environment variables.');
  }
} catch (e) {
  console.log('💡 Dotenv not found or not needed.');
}

const configContent = `// ────────────────────────────────────────────────────────────
// GRPHIWAVEMOTION — Generated Configuration
// This file is automatically generated during build.
// ────────────────────────────────────────────────────────────

window.EMAILJS_CONFIG = {
  PUBLIC_KEY:  "${process.env.EMAILJS_PUBLIC_KEY || ''}",
  SERVICE_ID:  "${process.env.EMAILJS_SERVICE_ID || ''}",
  TEMPLATE_ID: "${process.env.EMAILJS_TEMPLATE_ID || ''}"
};

console.log("🚀 System Configuration Active.");
`;

const configPath = path.join(__dirname, 'js', 'config.js');

try {
  fs.writeFileSync(configPath, configContent);
  console.log('✅ js/config.js successfully generated.');
} catch (err) {
  console.error('❌ Error generating config:', err);
  process.exit(1);
}
